#!/bin/bash

#ЗАПРОС ДАННЫХ
clear
read -ep "Enter your RU domain:"$'\n' ru_domain
read -ep "Enter your EN domain:"$'\n' en_domain
read -ep "Enter your EN ip:"$'\n' en_ip
read -ep "Enter your EN login:"$'\n' en_login
read -ep "Enter your EN password:"$'\n' en_password
apt update && apt install -y sqlite3 sshpass
read() { true; }

# НАСТРОЙКА EN
en_url=$(sshpass -p "$en_password" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$en_login@$en_ip" bash -s "$en_domain" << 'EOF'
    export TERM=xterm
    read() { true; }
    install_choice=1
    input_domain="$1"
    configure_ssh_input="n"
    configure_warp_input="n"
    source <(wget -qO- https://github.com/Akiyamov/xray-vps-setup/raw/main/vps-setup.sh) > /dev/null 2>&1
    echo "vless://$XRAY_UUID@$VLESS_DOMAIN:443?type=tcp&security=reality&pbk=$XRAY_PBK&fp=chrome&sni=$VLESS_DOMAIN&sid=&spx=%2F&flow=xtls-rprx-vision"
EOF
)

echo "$en_url"

# НАСТРОЙКА RU
install_choice=2
input_domain=$ru_domain
configure_ssh_input="n"
configure_warp_input="n"
source <(wget -qO- https://github.com/Akiyamov/xray-vps-setup/raw/main/vps-setup.sh)

# ВЫДАЧА ДАННЫХ
docker compose -f /opt/xray-vps-setup/docker-compose.yml down && docker compose -f /opt/xray-vps-setup/docker-compose.yml up -d
clear
echo "Dashboard: https://${VLESS_DOMAIN}/${MARZBAN_PATH}"
echo "User: xray_admin"
echo "Password: ${MARZBAN_PASS}"
